services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: tt_tienda
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgesql/data
